version: '3'

services:
  example-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: mortysmith
      POSTGRES_PASSWORD: ohjeezrick
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql